### ISSUE TITLE
Do you have an English version of this dataset?

### ISSUE THREAD

**Issue by lvxiaoxin** [bahadiri/Millionaire#2]
Hi Bahadir, I really appreciate your work for collecting such volume of data and make it open source. Do you have an English verison of this data? Especially for the questions statements and answers?

Thank you in advance!

**Comment by bahadiri** [comment]
Unfortunately no.

Due to Android penetration and single national broadcasting time, we deployed our app and collected our data from Turkey. So all the questions are the ones that appeared in the Turkish show during the year we run our experiment.

Another market with the aforementioned two properties and broadcasts in English is Nigeria which you may consider collecting data from.
